# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e6fe1add3c4e260b3728f252c16e909b36f706fa9e4513d395bb6e77c4da6f87b46ab5344d61aa7b125ddea803a28fb23104dd1f797a52756e6d34ff5717af08

test:
  secret_key_base: 4a02be1ba4fcd18abc53de8e11882543a6a33679efefe8f5bec30ed28d5fd34a1b46d893e87ec546a19e76685df880305225d58f528dc686671c210da6c5115e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
